config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events
  resources :users, only: [:new, :create, :show]
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations, source: :attendee

  validates :name, :description, :location, :date, presence: true

  scope :past, -> { where(['date < ?', Date.today]) }
  scope :upcoming, -> { where(['date > ?', Date.today]) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id, class_name: 'Event'
  has_many :invitations, foreign_key: :attendee
  has_many :attended_events, through: :invitations, source: :attended_event

  validates :name, presence: true, uniqueness: { case_sensitive: false },
                   length: { minimum: 4, maximum: 25 }

  scope :past, -> { where(['date < ?', Date.today]) }
  scope :upcoming, -> { where(['date > ?', Date.today]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:danger] = 'Logged in to perform this action'
    redirect_to root_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user, except: [:index]
  def index
    @past = Event.past
    @upcoming = Event.upcoming
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:notice] = 'Event has been created'
      redirect_to events_path
    else
      flash[:danger] = 'Something wrong'
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @users = User.all
    # @event.attendees.each do |e|
    #   @users = User.where.not(name: e.name).where.not(name: @event.creator.name)
    # end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(name: params[:session][:user])

    if @user
      session[:user_id] = @user.id
      session[:username] = @user.name
      redirect_to user_path(@user)
    else
      flash.now[:danger] = 'You are not an existing user.. Please register yourself first'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    redirect_to user_path(current_user) if logged_in?
  end

  def create
    @user = User.create(signup_params)
    if @user.save
      flash[:success] = 'Account is sucessfully created'
      session[:user_id] = @user.id
      session[:username] = @user.name
      redirect_to user_path(@user)
    else
      flash[:danger] = 'You are an existing user...  Please sign in'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @user_events = current_user.events
    @up_events = @user.attended_events.upcoming
    @prev_events = @user.attended_events.past
  end

  def destroy
    session[:user_id] = nil
    session[:username] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to root_path
  end

  private

  def signup_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_member
    res = ''
    if logged_in?
      res << link_to('Profile', user_path(session[:user_id]), class: 'btn btn-outline-success mr-3')
      res << (link_to 'Log out', logout_path, method: :delete,
                                              class: 'mr-2 btn btn-outline-danger')
    else
      res << (link_to 'Sign in', sign_in_path, class: 'mr-2 btn btn-outline-primary')
      res << (link_to 'Sign Up', new_user_path, class: 'mr-2 btn btn-outline-light')
    end
    res.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def doevents(name, events)
    render partial: name, locals: { obj: events }
  end

  def alluser(users)
    users.each do |user|
      concat(content_tag(:hr) + content_tag(:p, (link_to user.name, user_path(user))))
    end
  end

  def event_attendee(event)
    event.attendees.each do |e|
      concat(content_tag(:hr) + content_tag(:p, e.name))
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def created_events(user, name, events, title)
    render partial: name, locals: { obj: events, title: title } if user.events.size.positive?
  end

  def attended_events(user, name, events, title)
    return unless user.attended_events.size.positive?

    render partial: name, locals: { obj: events, title: title } if events.size.positive?
  end
end

app/views/events/_event.html.erb
<div class="row">
<% obj.each do |event| %>
  <div class="col-sm-12 col-md-6 col-lg-3 mb-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2"><%= link_to event.name, event_path(event) %></h5>
        <p class="card-text"><%= event.description %></p>
        <p><strong>Location: </strong><small class="card-text"><%= event.location %></small></p>
        <p><strong>Date: </strong>
        <small class="card-text">
            <strong><%= event.date.to_s.split(' ').first %> </strong>
            <em><%= event.date.to_s.split(' ')[1] %></em>
        </small>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="col-md-2"></div> 
  <div class="container">
    <h4 class="pb-3 mt-4">Upcoming Event</h4>
    <%= doevents('events/event', @upcoming)  %>

    <h4 class="pb-3 mt-4">Past Event</h4>
    <%= doevents('events/event', @past)  %>       
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1 class="text-center">Create Event</h1>
      
      <%= form_for(@event) do |f| %>
        <div class="form-group">
            <%= f.text_field :name, autofocus: true, placeholder: "Title of the Event", class: "form-control"  %>
        </div>
        <div class="form-group">
            <%= f.text_area :description, placeholder: "Event Description", class: "form-control"  %>
        </div>
        <div class="form-group">
            <%= f.text_field :location, placeholder: "Location of the event", class: "form-control"  %>
        </div>
          <div class="form-group">
            <%= f.datetime_select :date, :ampm => true, :minute_step => 15 %>
        </div>
        <div class="actions">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/events/show.html.erb
<div class="row mt-4">
  <div class="col-md-5 mb-2 ml-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2"><%= @event.name %><small class="float-right">Owner: <%= @event.creator.name  %> </small></h5>
        <p class="card-text"><%= @event.description %></p>
        <p><strong>Location: </strong><small class="card-text"><%= @event.location %></small></p>
        <p><strong>Date: </strong>
        <small class="card-text">
            <strong><%= @event.date.to_s.split(' ').first %> </strong>
            <em><%= @event.date.to_s.split(' ')[1] %></em>
        </small>
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-3 mb-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2">List of Attendees</h5>
        <% event_attendee(@event) %>
      </div>
    </div>
  </div>

  <div class="col-md-3 mb-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-2">Invite Users</h5>
        <% alluser(@users) %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back', :back %>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container">
  <%= link_to 'Home', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarMenu">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
       <%= link_to 'All Events', events_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Create Event', new_event_path, class: "nav-link" %>
        
      </li>

    </ul>
     <%= check_member %>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;700&display=swap" rel="stylesheet">
  </head>

  <body>

<%= render 'layouts/navbar' %>

 <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">
          &#215;
        </a>
        <%= msg %>
      </div>
    <% end %>

    <div id="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_user_events.html.erb
<h4 class="pb-3 mt-4"><%= title %></h4>
<div class="row">
<% obj.each do |event| %>
  <div class="col-sm-3 mb-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2"><%= link_to event.name, event_path(event) %></h5>
        <p class="card-text"><%= event.description %></p>
        <p><strong>Location: </strong><small class="card-text"><%= event.location %></small></p>
        <p><strong>Date: </strong>
        <small class="card-text">
            <strong><%= event.date.to_s.split(' ').first %> </strong>
            <em><%= event.date.to_s.split(' ')[1] %></em>
        </small>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1 class="text-center">For New User</h1>
      <%= form_for(@user) do |f| %>
        <div class="form-group">
            <%= f.text_field :name, autofocus: true, placeholder: "Enter your username", class: "form-control"  %>
        </div>
        <div class="actions">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center border-bottom mt-2">
	<h2>Signed in as:</h2> 
	<%= @user.name %>
</div>

<%= created_events(@user, 'users/user_events', @user_events, 'List of created events')  %>
<%= attended_events(@user, 'users/user_events', @up_events,'List of upcoming events')  %>
<%= attended_events(@user, 'users/user_events', @prev_events,'List of Previously attended events')  %>